### ISSUE TITLE
希望能支持标题中的单行代码显示

### ISSUE THREAD

**Issue by tisfeng** [MarMomento/typora-mo-theme#6]
![image](https://user-images.githubusercontent.com/25194972/106377978-cd670300-63db-11eb-9115-bf75094c1e49.png)

# 主题很漂亮，感谢作者！

如图，在标题中，单行代码没有适配，显得很小。

## 可以用 `guard`：在验证入口条件时

另外，`guard` 后面 `在验证`下面的下划线不知道怎么来的。。

**Comment by MarMomento** [comment]
谢谢，很高兴你能喜欢该主题。
1. 第一个问题(标题中的单行代码显示问题)：已经修复。
2. 第二个问题(标题下的下划线)：这个下划线是为了区分二级标题而特意加上的，当然如果你不喜欢的话，可以修改mo.css/mo-dark.css文件，注释或删除以下代码即可。
```css
#write h2:after {
  content: "";
  display: block;
  width: 6.25rem;
  height: 1px;
  margin: 0 auto;
  border-bottom: 1px solid #2f2f2f;
}
```
