### ISSUE TITLE
关于显示的优化

### ISSUE THREAD

**Issue by 184455** [MarMomento/typora-mo-theme#7]
首先非常感谢作者的无私分享，把这么完美的东西给大家用！
然后，我提一些个人使用这个主题的觉得可以优化点：
- 限制最外层容器的宽度；
- 去掉 TODO 完成以后的中划线；
- 标题：h1, h2, h3, h4, h5 的样式调整。

## 1、 限制最外层容器的宽度
首先来看一下没有加宽度限制的页面，感觉在美观度上不是很好：
![image](https://user-images.githubusercontent.com/30168717/116705347-032d7f00-a9ff-11eb-88ad-68d7abef2f3b.png)

**然后看一下加了宽度限制的效果**：
![image](https://user-images.githubusercontent.com/30168717/116705531-37a13b00-a9ff-11eb-9ba3-5e0356bf446e.png)

代码修改：
![image](https://user-images.githubusercontent.com/30168717/116705764-7afba980-a9ff-11eb-9534-47228a903583.png)

```css
#write {
  max-width: 1024px;
}
```

## 2、 去掉 TODO 完成以后的中划线
这一点，感觉和个人的使用习惯有关系。
TODO 我主要用来记录自己做的事情，做列表，记录问题的时候用来的。
不仅作为待办，还会记录很多比较杂乱的事情。
这个时候当TODO 很多的时候，满屏的中划线，感觉就很难受。可以感受一下：
![image](https://user-images.githubusercontent.com/30168717/116706783-95825280-aa00-11eb-8d6b-8760d45a1203.png)
![image](https://user-images.githubusercontent.com/30168717/116706941-bcd91f80-aa00-11eb-821f-cb52a890ee42.png)

关于这块的代码修改在这里：
![image](https://user-images.githubusercontent.com/30168717/116707196-fa3dad00-aa00-11eb-817b-4b66d7487f25.png)

## 3、标题：h1, h2, h3, h4, h5 的样式调整
关于标题的修改，效果主要看第一个问题的截图。
感觉标题的字体有一点大，居中和底部线条的效果可以修改一下！
PS：这里一点主要参考了官方 Github 主题的效果！

主要修改代码：
![image](https://user-images.githubusercontent.com/30168717/116707616-7506c800-aa01-11eb-870c-d838b83b4e29.png)

```css
#write h1,
#write h2 {
  text-align: left;
  margin-top: 2rem;
  margin-bottom: 1rem;
  border-bottom: 1px solid #eee;
}

#write h1 {
  font-size: 2.25rem;
}

#write h2 {
  font-size: 1.75rem;
}

#write h3 {
  font-size: 1.5rem;
}

#write h4 {
  font-size: 1.25em;
}

#write h5 {
  font-size: 1em;
}
```
